apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask        # must be the same value as the label in the template 
  template:
    metadata:
      labels:
        app: flask     # this label is assigned to each pod in the set
    spec:
      containers:
      - name: flask-container
        image: mattneedstolearn/duo-flask:latest
        ports:
        - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
  type: ClusterIP