apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app        # must be the same value as the label in the template 
  template:
    metadata:
      labels:
        app: flask-app    # this label is assigned to each pod in the set
    spec:
      containers:
      - name: flask-container
        image: mattneedstolearn/duo-task-flask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
  type: ClusterIP