apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginx      # must be the same value as the label in the template 
  template:
    metadata:
      labels:
        app: nginx      # this label is assigned to each pod in the set
    spec:
      volumes:
        - name: nginx-config-vol
          configMap: 
            name: nginx-config
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-vol
          mountPath: /etc/nginx/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |   # name of the file that will be mounted
    events {}
    http {
        server {
            listen 80;
            location / {
                proxy_pass http://flask-app:5500;
            }
            location /hello {
                return 200 "Hello World";
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer